name: ステップ 5

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write
  issues: write

env:
  REVIEW_FILE: ".github/steps/x-review.md"

jobs:
  find_exercise:
    if: |
      !github.event.repository.is_template
    name: 演習 Issue を検索
    uses: ./.github/workflows/ja-find-exercise-issue.yml
    with:
      issue-title-text: "演習: リポジトリ管理入門"

  check_step_work:
    name: Check step work
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update comment - checking work
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file .github/ja-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # START: Check practical exercise

      # Merging the pull request is enough to finish this step

      # END: Check practical exercise

      - name: Update comment - step finished - final review next
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file .github/ja-templates/step-feedback/lesson-review.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post_review_content:
    name: 振り返りを投稿
    runs-on: ubuntu-latest
    needs: [find_exercise, check_step_work]
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create comment - add review content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file ${{ env.REVIEW_FILE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish_exercise:
    name: 演習を完了
    needs: [find_exercise, post_review_content]
    uses: ./.github/workflows/ja-finish-exercise.yml
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}
      exercise-title: "リポジトリ管理入門"
      update-readme-with-congratulations: false

  disable_workflow:
    name: Disable this workflow
    needs: [find_exercise, post_review_content]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Disable current workflow
        run: gh workflow disable "${{github.workflow}}" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
